### PR TITLE
Proposing MIT license

### PR DESCRIPTION
**Pull request by edsadr**

### CODE REVIEW

**Comment by fmizzell** [comment]
@edsadr do you like MIT better than GPLv3?

**Comment by edsadr** [comment]
http://choosealicense.com/licenses/ MIT looks more open to me... GPL could be a bit restrictive

**Comment by fmizzell** [comment]
@edsadr True, the GPLv3 forces the software to stay open/free. I would like for modifications to this code to continue to be free and benefit others, instead of getting locked up in proprietary software. So, lets start with GPLv3 until someone makes a good argument for a more permissive license like LGPL or Apache 2.0. If you have any other reasons to prefer MIT let me know, otherwise lets go with GPLv3. Also the Free software foundation recommends Apache 2.0 over MIT: https://www.gnu.org/licenses/license-list.html#X11License

**Comment by fmizzell** [comment]
@edsadr I created a PR with GPLv3 as the license. Let me know if you have any fundamental objections and we can go from there. https://github.com/fmizzell/systemizer/pull/8

**Pull request closed without merging**
